const ROLE_STORY_SCHEMA_VERSION = 5
const BOOK_TEXT_SCHEMA_VERSION = 5
const PLOT_TEXT_SCHEMA_VERSION = 8
const MAP_TEXT_SCHEMA_VERSION = 6
const ANECDOTE_TEXT_SCHEMA_VERSION = 3
const CARD_TEXT_SCHEMA_VERSION = 4
const RELIC_TEXT_SCHEMA_VERSION = 4
const WEAPON_TEXT_SCHEMA_VERSION = 4
const BACKPACK_TEXT_SCHEMA_VERSION = 5

const INTERACTIVE_DIALOGUE_PIPELINE_VERSION = 4
const INTERACTIVE_DIALOGUE_PIPELINE_VERSIONS = {
  plot: 6,
  map: 2,
  anecdote: 5
}

const INTERACTIVE_PARSE_PIPELINE_KEYS = {
  plot: 'plotInteractiveParse',
  map: 'mapInteractiveParse',
  anecdote: 'anecdoteInteractiveParse'
}

export {
  ROLE_STORY_SCHEMA_VERSION,
  BOOK_TEXT_SCHEMA_VERSION,
  PLOT_TEXT_SCHEMA_VERSION,
  MAP_TEXT_SCHEMA_VERSION,
  ANECDOTE_TEXT_SCHEMA_VERSION,
  CARD_TEXT_SCHEMA_VERSION,
  RELIC_TEXT_SCHEMA_VERSION,
  WEAPON_TEXT_SCHEMA_VERSION,
  BACKPACK_TEXT_SCHEMA_VERSION,
  INTERACTIVE_DIALOGUE_PIPELINE_VERSION,
  INTERACTIVE_DIALOGUE_PIPELINE_VERSIONS,
  INTERACTIVE_PARSE_PIPELINE_KEYS
}
